version: '3.8'

services:
  wechat-qrcode:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - ./data:/root/data
      - ./configs:/root/configs
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
      - BASE_URL=http://localhost:8083
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"] 
      interval: 30s
      timeout: 10s
      retries: 3 